name: credit cart approval

channels:
  - defaults
dependencies:
  - pandas==1.0.3
  - numpy==1.16.4
  - Click==7.0
  - scikit-learn==0.21.2
  - joblib==0.14.1
  - pip
  - pip:
      - mlflow==1.8.0
      - pandas-profiling==2.6.0

